version: v1.1

llm:
  provider: openai
  config:
    model: gpt-4o-mini
    temperature: 0.1

embedder:
  provider: openai
  config:
    model: text-embedding-3-small

vector_store:
  provider: pgvector
  config:
    dbname: ltm_vectors
    host: postgres
    port: 5432
    user: ltm_user
    password: ltm_password
    table_name: ltm_embeddings